#! /usr/bin/env python3
"""Updates latest statistics."""

from syslib import script

from digsigdb import refresh_termstats


@script
def main():
    """Refreshes the terminal statistics,"""

    refresh_termstats()


if __name__ == '__main__':
    main()
